const pelis = [
    { id: 1, name: 'Animales Fantasticos y donde encontrarlos', image: 'img/Animales_Fantasticos_1.jpg', informacion: "En 1926, el mago experto en zoología Newt Scamander hace una breve parada en Nueva York mientras viaja catalogando y capturando criaturas mágicas por el mundo. Jacob, un humano corriente, provoca por error que las criaturas escapen y se oculten por la ciudad. Scamander tendrá que atraparlas de nuevo, antes de que causen problemas." },
    { id: 2, name: 'Animales Fantasticos: Los crímenes de Grindelwald', image: 'img/Animales_Fantasticos_2.jpg', informacion: "El joven mago, Newt Schamander, junto con sus compañeros Jacob Kowalski y las hermanas Tina y Queenie Goldstein, tendrá que hacer frente a las nuevas amenazas de Grindelwald. El mago ha escapado y está reuniendo a un grupo de seguidores que no sospecha de sus verdaderas intenciones: alzar a los magos por encima de las criaturas no mágicas." },
    { id: 3, name: 'Animales Fantasticos: Los secretos de Dumbledore', image: 'img/Animales_Fantasticos_3.jpg', informacion: "La historia tiene lugar en Río de Janeiro, Brasil y conduce a la participación del Mundo Mágico en la Segunda Guerra Mundial." },
    { id: 4, name: 'El club de la pelea', image: 'img/El_club_de_la_pelea.jpg', informacion: "Un empleado de oficina insomne en busca de una manera de cambiar su vida se cruza con un vendedor y crean un club de lucha clandestino como forma de terapia." },
    { id: 5, name: 'El señor de los anillos: La comunidad del anillo', image: 'img/El_Señor_de_los_Anillos_1.jpg', informacion: "En la Tierra Media, el Señor Oscuro Sauron forjó los Grandes Anillos del Poder y creó uno con el poder de esclavizar a toda la Tierra Media. Frodo Bolsón es un hobbit al que su tío Bilbo hace portador del poderoso Anillo Único con la misión de destruirlo. Acompañado de sus amigos, Frodo emprende un viaje hacia Mordor, el único lugar donde el anillo puede ser destruido. Sin embargo, Sauron ordena la persecución del grupo para recuperar el anillo y acabar con la Tierra Media." },
    { id: 6, name: 'El señor de los anillos: Las dos Torres', image: 'img/El_Señor_de_los_Anillos_2.jpg', informacion: "Los hobbits Frodo y Sam descubren que Gollum les está siguiendo. La criatura les promete guiarlos hasta las puertas de Mordor si después lo dejan libre. Aragorn, el elfo Legolas y Gimli el enano llegan al reino de Rohan y descubren que el rey Theoden está bajo el conjuro de Sarumán. El traidor quiere el control del reino para continuar con sus planes en Mordor, a la espera de la guerra en la Tierra Media." },
    { id: 7, name: 'El señor de los anillos: El retorno del Rey', image: 'img/El_Señor_de_los_Anillos_3.jpg', informacion: "La batalla por la Tierra Media ha empezado. Las fuerzas de Saruman han sido destruidas y por primera vez parece que hay una pequeña esperanza. Sin embargo, el poder de Sauron crece y su interés se centra en Gondor, el último reducto de los hombres, cuyo heredero es Aragorn. Mientras, Frodo y Sam, guiados por Gollum, siguen su peligrosa misión a través de Mordor para destruir el anillo." },
    { id: 8, name: 'Harry Potter y la piedra Filosofal', image: 'img/Harry_Potter_1.jpg', informacion: "El día en que cumple once años, Harry Potter descubre que es hijo de dos conocidos hechiceros, de los que ha heredado poderes mágicos. Deberá acudir entonces a una famosa escuela de magia y hechicería: Howards." },
    { id: 9, name: 'Harry Potter y la cámara secreta', image: 'img/Harry_Potter_2.jpg', informacion: "Terminado el verano, Harry no ve la hora de abandonar la casa de sus odiosos tíos. Inesperadamente se presenta en su dormitorio Dobby, un elfo doméstico, que le anuncia que correrá un gran peligro si vuelve a Hogwarts." },
    { id: 10, name: 'Harry Potter y el prisionera de Azkaban', image: 'img/Harry_Potter_3.jpg', informacion: "El tercer año de estudios de Harry en Hogwarts se ve amenazado por la fuga de Sirius Black de la prisión para magos de Azkaban. Se trata de un peligroso mago que fue cómplice de Lord Voldemort y que intentará vengarse de Harry Potter." },
    { id: 11, name: 'Harry Potter y el caliz de fuego', image: 'img/Harry_Potter_4.jpg', informacion: "Tras las evidencias de que Voldemort ha regresado, Harry se verá envuelto en el tradicional Torneo de los Tres Magos. Con ayuda de Ron y Herminone, se preparará para competir en una nueva lucha que él no ha elegido." },
    { id: 12, name: 'Harry Potter y la orden del Fénix', image: 'img/Harry_Potter_5.jpg', informacion: "Cuando la ignorancia de una nueva profesora deja a Hogwarts sin la preparación suficiente para luchar contra el demonio, Harr le enseña a un pequeño grupo de estudiantes a defenderse en contra de las artes oscuras." },
    { id: 13, name: 'Harry Potter y el misterio del príncipe Mestizo', image: 'img/Harry_Potter_6.jpg', informacion: "Sexta entrega de la saga del joven mago, en la que Harry descubre un poderoso libro y, mientras trata de descubrir sus orígenes, colabora con Dumbledore en la búsqueda de una serie de objetos mágicos que ayudarán en la destrucción de Lord Voldemort." },
    { id: 14, name: 'Harry Potter y las reliquias de la muerte - Parte 1', image: 'img/Harry_Potter_7.jpg', informacion: "Harry, Ron y Hermione dejan Hogwarts para seguir con su misión de destruir los Horcruxes, el secreto del poder y la inmortalidad de Voldemort." },
    { id: 15, name: 'Harry Potter y las reliquias de la muerte - Parte 2', image: 'img/Harry_Potter_8.jpg', informacion: "La batalla entre las fuerzas del bien y del mal del mundo mágico se convierte en una guerra que no deja a nadie indiferente. Harry Potter es quien tiene que hacer el último sacrificio antes de enfrentarse al malvado Voldemort." },
    { id: 16, name: 'El Hobbit: Un viaje inesperado', image: 'img/Hobbit_1.jpg', informacion: "El hobbit Bilbo Bolsón vive una vida tranquila hasta que el mago Gandalf aparece y le encomienda una misión: unirse a un grupo de enanos para recuperar un tesoro que les pertenece. El tesoro está guardado por un dragón en el reino de Erebor, que antes pertenecía a los enanos. Durante el viaje, Bilbo y los enanos tendrán que enfrentarse a orcos y otros peligros, como Gollum y un anillo de oro que tiene un poder extraordinario." },
    { id: 17, name: 'El Hobbit: La desolación de Smaug', image: 'img/Hobbit_2.jpg', informacion: "Bilbo y sus compañeros continúan su viaje hacia el este y enfrentan muchos peligros de camino a la Montaña Solitaria, culminando con un encuentro con el temible dragón Smaug." },
    { id: 18, name: 'El Hobbit: La batalla de los cinco ejércitos', image: 'img/Hobbit_3.jpg', informacion: "Los enanos de Erebor han reclamado la riqueza de su patria, pero ahora deben enfrentarse a las consecuencias de haber liberado al temible dragón Smaug. Mientras Bilbo, Thorin y parte de la Compañía de los Enanos se refugian en la Colina del Cuervo, Smaug ataca la Ciudad del Lago, sembrando la muerte y la destrucción." },
    { id: 19, name: 'Jumanji', image: 'img/Jumanji_1.jpg', informacion: "Alan Parris queda atrapado en un juego de mesa mágico y muy antiguo llamado Jumanji. Nadie cree a su compañera de juego cuando cuenta lo ocurrido. Veinticinco años más tarde, es liberado por dos niños, pero una manada de animales exóticos queda también en libertad." },
    { id: 20, name: 'Jumanji: En la selva', image: 'img/Jumanji_2.jpg', informacion: "Las aventuras continúan en el fantástico mundo del juego Jumanji, donde nada es lo que parece. En esta ocasión, los jugadores vuelven al juego, pero sus personajes se han intercambiado entre sí, lo que ofrece un curioso plantel: los mismos héroes con distinta apariencia. Pero, ¿dónde está el resto de la gente?" },
    { id: 21, name: 'Jumanji: El siguiente nivel', image: 'img/Jumanji_3.jpg', informacion: "Las aventuras continúan en el fantástico mundo del juego Jumanji, donde nada es lo que parece. En esta ocasión, los jugadores vuelven al juego, pero sus personajes se han intercambiado entre sí, lo que ofrece un curioso plantel: los mismos héroes con distinta apariencia. Pero, ¿dónde está el resto de la gente?" },
    { id: 22, name: 'Mision Imposible II', image: 'img/Mision_imposible_1.jpg', informacion: "Ethan Hunt es un espía capaz de llevar a cabo las misiones más peligrosas con la máxima eficacia. Ahora debe participar en una dificilísima misión: evitar la venta de un disco robado que contiene información secreta de importancia vital." },
    { id: 23, name: 'Mision Imposible III', image: 'img/Mision_imposible_2.jpg', informacion: "Ethan Hunt debe impedir que un exagente convertido en terrorista internacional se haga con un virus mortal y lo introduzca en Australia." },
    { id: 24, name: 'Mision Imposible: Protocolo fantasma', image: 'img/Mision_imposible_3.jpg', informacion: "Tras haber llevado a cabo diversas misiones, el agente especial Ethan Hunt se ha retirado del servicio activo y se ha prometido con su amada, Julia. Sin embargo, cuando es secuestrado por uno de los agentes entrenados por él, vuelve de nuevo a la acción. También tiene que enfrentarse a Owen Davian, un individuo sin escrúpulos que trafica con armas y con información." },
    { id: 25, name: 'Mision Imposible: Nación secreta', image: 'img/Mision_imposible_4.jpg', informacion: "El agente Hunt, acusado de un atentado terrorista, es desautorizado junto con toda la organización, al poner en marcha el Presidente el Protocolo Fantasma. Abandonado sin recursos, Hunt emprende una misión con un equipo formado por fugitivos." },
    { id: 26, name: 'Mision Imposible: Repercusión', image: 'img/Mision_imposible_5.jpg', informacion: "Ethan Hunt y su equipo descubren quién está detrás de los últimos ataques terroristas: el Sindicato, una organización internacional secreta formada por antiguos agentes dados por muertos. Justo en ese momento, la CIA consigue que el Gobierno cierre el FMI, convirtiendo a Ethan en fugitivo." },
    { id: 27, name: 'Mision Imposible: Sentencia mortal I', image: 'img/Mision_imposible_6.jpg', informacion: "El espía Ethan Hunt recibe en Belfast un mensaje secreto: los autodenominados Apóstoles, seguidores del anarquista Solomon Lane, capturado por Hunt hace dos años, están intentando hacerse con tres núcleos de plutonio para crear potentes armas nucleares muy fáciles de transportar." },
    { id: 28, name: 'Mision Imposible: Sentencia mortal II', image: 'img/Mision_imposible_7.jpg', informacion: "Ethan debe detener a una inteligencia artificial que todas las potencias mundiales codician, la cual se ha vuelto tan poderosa que se rebeló contra sus creadores y ahora es una amenaza en sí misma." },
    { id: 29, name: 'Rápidos y Furiosos', image: 'img/Rapidos_Furiosos_1.jpg', informacion: "Cada noche, Los Ángeles es testigo de alguna carrera de coches. Últimamente ha aparecido un nuevo corredor, todos saben que es duro y que es rápido, pero lo que no saben es que es un detective con la determinación de salir victorioso." },
    { id: 30, name: 'Más rapidos y más Furiosos', image: 'img/Rapidos_Furiosos_2.jpg', informacion: "Brian O'Conner ayuda a la policía de Miami y se infiltra en el mundo de las carreras ilegales, esperando así redimirse ante sus superiores." },
    { id: 31, name: 'Rapidos y Furiosos: Reto Tokio', image: 'img/Rapidos_Furiosos_3.jpg', informacion: "Shaun Boswell es un chico rebelde cuya única conexión con el mundo es a través de las carreras ilegales. Cuando la policía le amenaza con encarcelarle, se va a pasar una temporada con su tío, un militar destinado en Japón." },
    { id: 32, name: 'Rapidos y Furiosos 4', image: 'img/Rapidos_Furiosos_4.jpg', informacion: "El ex convicto Dominic Toretto se une a su viejo adversario, Brian O'Conner, que ahora trabaja para el FBI en Los Ángeles, con el fin de infiltrarse en una organización criminal que se dedica a introducir heroína en la ciudad." },
    { id: 33, name: 'Rapidos y Furiosos: Sin control', image: 'img/Rapidos_Furiosos_5.jpg', informacion: "Los viejos amigos Dominic y Mia Toretto y Brian O'Conner se encuentran ahora en Río de Janeiro, donde pretenden dar un último golpe con el fin de obtener su libertad. Para ello reúnen a un grupo de élite de pilotos experimentados." },
    { id: 34, name: 'Rapidos y Furiosos 6', image: 'img/Rapidos_Furiosos_6.jpg', informacion: "El agente Hobbs les ofrece a Toretto y a su antiguo equipo el perdón total, si ellos lo ayudan a atrapar a una banda de conductores mercenarios cuyo líder es Shaw, y la segunda al mando es alguien a quien todos ellos conocen." },
    { id: 35, name: 'Rapidos y Furiosos 7', image: 'img/Rapidos_Furiosos_7.jpg', informacion: "Hace un año que Dominic y Brian fueron indultados y pudieron regresar a los Estados Unidos. Después de su llegada desean adaptarse a su nueva vida dentro de la legalidad, pero las cosas no son tan fáciles. Dom quiere acercarse a Letty y Brian se acostumbra a la vida en una urbanización con Mia y su hijo. Sin embargo, la tranquilidad no dura mucho y todo cambia cuando un asesino británico entra en sus vidas para convertirse en su mayor enemigo." },
    { id: 36, name: 'Rapidos y Furiosos 8', image: 'img/Rapidos_Furiosos_8.jpeg', informacion: "Con Dom y Letty de luna de miel, Brian y Mia retirados y el resto de la pandilla viviendo en paz, parece que todo está tranquilo. Sin embargo, una misteriosa mujer seducirá a Dom para adentrarlo en el mundo del crimen y traicionar a la pandilla. Ahora tendrán que unirse para traer a casa al hombre que los convirtió en una familia y detener a Cipher de desatar el caos." },
    { id: 37, name: 'Rapidos y Furiosos 9', image: 'img/Rapidos_Furiosos_9.jpeg', informacion: "Dom Toretto lleva una vida tranquila, pero sabe que el peligro siempre acecha. Esta vez, Dom y el equipo se reúnen para impedir un complot a escala mundial, liderado por uno de los asesinos más peligrosos y hábiles al volante a los que se han enfrentado; un hombre que además es el hermano desaparecido de Dom, Jako." },
    { id: 38, name: 'Rapidos y Furiosos X', image: 'img/Rapidos_Furiosos_10.jpg', informacion: "Comienza el final del camino. Rápidos Y Furiosos X, la décima película de la saga de Rápidos y Furiosos, presenta los capítulos finales de una de las franquicias del cine más famosas y populares mundialmente, ahora en su tercera década y aún fuerte con el mismo elenco y personajes principales que cuando comenzó. A lo largo de muchas misiones y contra cualquier adversidad, Dom Toretto (Vin Diesel) y su familia han sido más inteligentes, más astutos por" },
    { id: 39, name: 'Rapidos y Furiosos: Bandoleros', image: 'img/Rapidos_Furiosos_Bandoleros.jpg',informacion: "Mientras tanto, Dom y Tego se reúnen con el político local Elvque Elvis le dice que si le da la gasolina a la gente, Dios lo bendecirá. Mientras la fiesta en el club continúa, Han y Cara se marchan juntos y Dom se besa con dos chicas, pero es sorprendido por la llegada de Letty Ortiz (Michelle Rodriguez). Después Dom comenta que la vida cambia, pero a su vez Letty le pregunta dónde dormirá. Dom deja a las chicas y se reúne con Lett en auto hac"},
    { id: 40, name: 'Rapidos y Furiosos: Hobbs and Shaw', image: 'img/Rapidos_Furiosos_Hobbs&Shaw.jpeg', informacion: "Spin-off de la franquicia cinematográfica Rapidos y Furiosos, que sigue al policía estadounidense Hobbs y al mercenario británico Shaw. En el pasado, Hobbs encarceló a Shaw después de que este intentara matarlo. Ahora deben aliarse para combatir al terrorista Brixton, que tiene una fuerza sobrenatural." },
];

let contenedorCards = document.getElementById("contenedor");
let CartasParaHTML = "";

for(let i = 0; i < pelis.length; i++){
    CartasParaHTML += crearcards(pelis[i]);
}

contenedorCards.innerHTML = CartasParaHTML;

function crearcards(peli){
    let cards = document.createElement('div');
    cards.classList.add('card');

    let id = document.createElement('div');
    let name = document.createElement('p');
    let image = document.createElement('img');
    let info = document.createElement('p');

    id.innerText = peli.id;
    name.innerText = peli.name;
    image.src = peli.image;
    info.innerText = peli.informacion;

    cards.append(id, name, image, info);
    return cards.outerHTML;
}